server:
  port: 8090
  forward-headers-strategy: FRAMEWORK

spring:
  session:
    store-type: redis
    redis:
      flush-mode: on-save
      namespace: session
    timeout: 30m
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  thymeleaf:
    cache: false

app:
  auth-service-url: http://localhost:8081
